DROP TABLE IF EXISTS GLOBAL_MODULE;

CREATE TABLE GLOBAL_MODULE (
  ID   INT AUTO_INCREMENT NOT NULL,
  NAME VARCHAR(20)        NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY GLOBAL_MODULES(NAME)
)
  ENGINE = innodb
  DEFAULT CHARACTER SET utf8;
